# Generated by Django 3.1.7 on 2021-03-10 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListHarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('halaman', models.CharField(max_length=100)),
                ('biaya_setup', models.CharField(max_length=50)),
                ('hosting', models.CharField(max_length=50)),
                ('maintenance', models.TextField()),
                ('tambahan', models.TextField()),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PilihanHarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempatKursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('t_content', models.CharField(max_length=150)),
                ('t_img', models.ImageField(upload_to='img')),
                ('time_up', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time_upload', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='img')),
                ('publish', models.BooleanField()),
                ('views', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=50, verbose_name='myblog_post.urls')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.author')),
                ('kategori', models.ManyToManyField(to='myblog.Kategori')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
