# Generated by Django 3.1.7 on 2021-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=50, verbose_name='myblog_post.urls'),
        ),
    ]
