# Generated by Django 3.1.7 on 2021-03-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempatkursus',
            options={'ordering': ['-pk']},
        ),
    ]
