# Generated by Django 3.1.7 on 2021-03-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210310_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempatkursus',
            options={},
        ),
    ]
