# Generated by Django 3.1.7 on 2021-03-10 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210310_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempatkursus',
            name='time_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
