# Generated by Django 3.1.7 on 2021-03-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
