# Generated by Django 3.1.7 on 2021-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20210308_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0, verbose_name='myblog_post.urls'),
        ),
    ]
